Downloader: Fix pop from empty set
When an image is not found, we throw a cryptic error message. This
fixes that, giving a clearer error.

	[misc-tools] Running shell script
	+ set -o pipefail
	+ ./download-image --proxy **** --location **** --type kvm channel://devel
	+ tee /j/workspace/lum_PR-512-QIGXQKGO62MB6JA3Q3D4T/logs/caasp-kvm-prepare-image-caasp.log
	Traceback (most recent call last):
	  File "./download-image", line 279, in <module>
	    use_channel_file(args)
	  File "./download-image", line 67, in use_channel_file
	    remote_url = get_channel_url(args)
	  File "./download-image", line 247, in get_channel_url
	    "image": parser.get_image()
	  File "./download-image", line 44, in get_image
	    return self.images.pop().strip(" ")
	KeyError: 'pop from an empty set'
	script returned exit code 1

(cherry picked from commit b088e05475b15dcef323220b8c34252c371b1766)