reduce worker number
as we have increased the admin ram in CI we need to scale down
on the addNode job

Error: cannot set up guest memory 'pc.ram': Cannot allocate memory

Signed-off-by: Maximilian Meister <mmeister@suse.de>